### PR TITLE
Fixed overrideContent feature in InlineToolbar

### LINKED ISSUE #967: Headline buttons are broken in the Custom Inline Toolbar Example
These buttons "HeadlineOneButton", "HeadlineTwoButton", "HeadlineThreeButton" are broken in the [Custom Inline Toolbar Example](https://www.draft-js-plugins.com/plugin/inline-toolbar).

Tested on Chrome and Firefox.

### PR DESCRIPTION
**Pull request by juliankrispel**
## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

fixes #967

### CODE REVIEW

**Comment by juliankrispel** [comment]
thanks for the review @amannn :heart: I can't remember exactly - but it was another fix (via setTimeout)...

File: docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js [hunk 1]
```diff
@@ -47,6 +47,10 @@ class HeadlinesPicker extends Component {
 }
 
 class HeadlinesButton extends Component {
+  // When using a click event inside overriden content we have
+  // to cancel click events from the toolbar itself unfortunately
```
Comment (amannn) [inline docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js]: There's a small typo: "overridden"

Since this comment is in the docs and is supposed to educate users, what about something like: "When using a click event inside overridden content, mouse down events needs to be prevented so the focus stays in the editor and the toolbar remains visible."?

Comment (amannn) [reply docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js]: @juliankrispel Don't you think this should be updated?

Comment (juliankrispel) [reply docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js]: @amann I did :) - you're looking at the outdated version ;)

Comment (juliankrispel) [reply docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js]: @amannn are you sure you don't want to join our fortnightly meetings?  ;)

Comment (amannn) [reply docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js]: Ah – sorry, my bad! Haha, I'll think it over ;-)
