### PR TITLE
fixed refs for draft-js-resizeable-plugin and draft-js-side-toolbar-plugin

### LINKED ISSUE #1020: Image resizing bugs in Firefox
## Use-case/Problem

The draft-js-resizeable-plugin seems to have some bugs in Firefox. You can see the bugs on the examples in the documentation ("Alignment + Resize + Focus + Drag'n'Drop + Drag'n'Drop Upload Example" at https://www.draft-js-plugins.com/plugin/image).

When you try to resize the image, you can hover your mouse on the edge of the image and the cursor turns into the resize cursor, but when you click and drag, it drags and drops instead of resizing, sometimes adding extra blank lines after the image, sometimes copying and pasting the image.

### LINKED ISSUE #1021: Image resizing stop working since draft.js 0.10.5
The two live demos below are exactly same and use draft-js-plugins demo code.
The only difference is one using draft.js 0.10.4 and another one using draft.js 0.10.5

[Live demo using draft.js 0.10.4](https://stackblitz.com/edit/react-gxcpfp), can resize image, 
[Live demo using draft.js 0.10.5](https://stackblitz.com/edit/react-qoswxb), failed to resize image

### PR DESCRIPTION
**Pull request by freedomlang**
## Checklist

- [x] Fix any eslint errors that occur
- [x] Update change-log for every plugin you touch
- [x] Add/Update tests if you add/change new functionality
- [x] Add/Update docs if you add/change functionality
- [x] Enable "Allow edits from maintainers" for this PR

## Use-case/Problem

resolve #1021 #1023 #1024 #1039 

The ref attribute in draft-js-plugins-editor is no longer a string since [cf6653f196c0](https://github.com/draft-js-plugins/draft-js-plugins/commit/cf6653f196c0b23b191b03f968d30eace8e62d4b#diff-2180aea2d91b1762f617f66247191a4c)，so `.refs.editor` can not access the editor and cause subsequent errors.

## Implementation

Use `.editor` instead of `.refs.editor`.

### CODE REVIEW

**Comment by juliankrispel** [comment]
@DaveWelling let me test this before I merge it, will have a look today

**Comment by freedomlang** [comment]
@juliankrispel Is there any news ?

**Comment by andela-engmkwalusimbi** [comment]
@juliankrispel did you get to test this?

**Comment by juliankrispel** [comment]
ugh - would do right now but have work on - I'll still get a chance this week I'm sure!

**Comment by andela-engmkwalusimbi** [comment]
Sure. Looking forward to it

**Comment by davidfloegel** [comment]
@juliankrispel hey mate, I know you're busy but any chance we can get this merged?
We're about to launch our blog using the draftjs editor and your great plugins but this will be holding us up.

Appreciate it!

File: draft-js-resizeable-plugin/src/createDecorator.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export default ({ config, store }) => (WrappedComponent) => class BlockResizeabl
     const doDrag = (dragEvent) => {
       let width = (startWidth + dragEvent.clientX) - startX;
       let height = (startHeight + dragEvent.clientY) - startY;
-      const block = store.getEditorRef().refs.editor;
+      const block = store.getEditorRef().editor;
```
Comment (juliankrispel) [inline draft-js-resizeable-plugin/src/createDecorator.js]: changing this throws an error for me on line 93 `clientWidth of undefined` - have you tested this?

Comment (juliankrispel) [reply draft-js-resizeable-plugin/src/createDecorator.js]: this happens both in firefox and chrome btw ...

**Comment by juliankrispel** [comment]
so just to be clear - the resizable bug on firefox is not fixed by this.

**Comment by juliankrispel** [comment]
sry but I tested this and actually it's not fixing anything - rather than that it's causing a reference error - the `refs` are still intact and work as they should @davidfloegel @andela-engmkwalusimbi and @DaveWelling can you let me know what problem you actually need fixed (is i the resize image problem in firefox?) Feel free to hit me up on slack

File: draft-js-resizeable-plugin/src/createDecorator.js (hunk 1 above)
Comment (freedomlang) [reply draft-js-resizeable-plugin/src/createDecorator.js]: draft-js-plugin-editor is 2.0.4
draft-js-resizeable-plugin: 2.0.1

get error for `store.getEditorRef().refs.editor`
tested on chrome and firefox

**Comment by juliankrispel** [comment]
having tested this and since it actually doesn't seem to fix anything - I'm closing this for now. I'm considering that I just couldn't reproduce it for some weird reason so lmk what your guys's findings are and if there's a case we can reopen this pr.

File: draft-js-resizeable-plugin/src/createDecorator.js (hunk 1 above)
Comment (juliankrispel) [reply draft-js-resizeable-plugin/src/createDecorator.js]: @freedomlang mind setting up a codesandbox for this? Would help a lot with fixing this

Comment (freedomlang) [reply draft-js-resizeable-plugin/src/createDecorator.js]: the error is `Cannot read property 'editor' of undefined`

**Comment by juliankrispel** [comment]
I just spent 30 minutes trying to reproduce these issues but couldn't - if someone could post a link to a codesandbox here reproducing the issue that'd help a bunch!

**Comment by freedomlang** [comment]
making a demo on codesanbox to reproduce it

**Comment by davidfloegel** [comment]
@juliankrispel I'm so sorry mate, I just checked myself on my mac with firefox and it seems to work. We only tested on linux machines before and there is definitely an issue.

@freedomlang and @juliankrispel  which OS are you on?

**Comment by freedomlang** [comment]
@davidfloegel Mac os 10.13.3

**Comment by davidfloegel** [comment]
However there seems to be an issue with unfocussing an selected image and the alignment of images..

**Comment by freedomlang** [comment]
@juliankrispel do not have a good network to access codesandbox, would try it later!

**Comment by juliankrispel** [comment]
@davidfloegel yes - but unrelated to this ...

**Comment by freedomlang** [comment]
@juliankrispel here is the [codesandbox](https://codesandbox.io/s/rl08z51z4m)

**Comment by juliankrispel** [comment]
ok I figured out what the problem is - it's the react 16 upgrade basically, and how refs have changed. But this breaks react 15 support - so I'm adding a commit that caters for both. Thanks again!

**Comment by juliankrispel** [comment]
okidokes fixed the remaining issues, releasing in a few minutes folks cc @davidfloegel @freedomlang @andela-engmkwalusimbi 

thanks everyone 👍
